services:
  - type: web
    name: my-web-service
    env: docker
    plan: starter
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: MY_VAR
        value: my_value  # Nếu cần thiết lập biến môi trường
    ports:
      - 8080  # Cổng mà dịch vụ của bạn sẽ lắng nghe
